---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - iomesh.iomesh.com
  resources:
  - iomeshvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iomesh.iomesh.com
  resources:
  - iomeshvolumes/finalizers
  verbs:
  - update
- apiGroups:
  - iomesh.iomesh.com
  resources:
  - iomeshvolumes/status
  verbs:
  - get
  - patch
  - update
