apiVersion: iomesh.iomesh.com/v1
kind: IOMeshVolume
metadata:
  name: iomeshvolume-sample
spec:
  node: jeffwu-worker02
  pvc: 
    storageClassName: iomesh-csi-driver 
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
